// Türkiye il ve ilçe verileri
const turkeyData: Record<string, string[]> = {
  "Adana": ["Seyhan", "Yüreğir", "Çukurova", "Sarıçam", "Karaisalı", "Ceyhan", "Kozan", "İmamoğlu", "Aladağ", "Feke", "Karataş", "Pozantı", "Saimbeyli", "Tufanbeyli", "Yumurtalık"],
  "Adıyaman": ["Merkez", "Besni", "Gölbaşı", "Kahta", "Çelikhan", "Gerger", "Samsat", "Sincik", "Tut"],
  "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ", "Çay", "Sultandağı", "İhsaniye", "Sinanpaşa", "Şuhut", "Başmakçı", "Bayat", "Çobanlar", "Dazkırı", "Evciler", "Hocalar", "İscehisar", "Kızılören"],
  "Ağrı": ["Merkez", "Doğubayazıt", "Patnos", "Eleşkirt", "Diyadin", "Hamur", "Taşlıçay", "Tutak"],
  "Amasya": ["Merkez", "Merzifon", "Suluova", "Göynücek", "Gümüşhacıköy", "Hamamözü", "Taşova"],
  "Ankara": ["Altındağ", "Çankaya", "Etimesgut", "Keçiören", "Mamak", "Pursaklar", "Sincan", "Yenimahalle", "Gölbaşı", "Polatlı", "Beypazarı", "Çubuk", "Haymana", "Kahramankazan", "Kızılcahamam", "Nallıhan", "Şereflikoçhisar", "Akyurt", "Ayaş", "Bala", "Çamlıdere", "Elmadağ", "Evren", "Güdül", "Kalecik"],
  "Antalya": ["Muratpaşa", "Kepez", "Konyaaltı", "Aksu", "Döşemealtı", "Alanya", "Manavgat", "Serik", "Kumluca", "Kaş", "Kemer", "Finike", "Gazipaşa", "Demre", "Elmalı", "Gündoğmuş", "İbradı", "Korkuteli", "Akseki"],
  "Artvin": ["Merkez", "Arhavi", "Borçka", "Hopa", "Şavşat", "Yusufeli", "Ardanuç", "Murgul"],
  "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "İncirliova", "Germencik", "Çine", "Bozdoğan", "Sultanhisar", "Buharkent", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Kuyucak", "Yenipazar"],
  "Balıkesir": ["Altıeylül", "Karesi", "Bandırma", "Edremit", "Gönen", "Erdek", "Burhaniye", "Ayvalık", "Bigadiç", "Dursunbey", "Havran", "İvrindi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Sındırgı", "Susurluk", "Balya"],
  "Bilecik": ["Merkez", "Bozüyük", "Osmaneli", "Gölpazarı", "Pazaryeri", "Söğüt", "İnhisar", "Yenipazar"],
  "Bingöl": ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yayladere", "Yedisu"],
  "Bitlis": ["Merkez", "Tatvan", "Adilcevaz", "Ahlat", "Güroymak", "Hizan", "Mutki"],
  "Bolu": ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen", "Dörtdivan", "Kıbrıscık", "Seben", "Yeniçağa"],
  "Burdur": ["Merkez", "Bucak", "Gölhisar", "Tefenni", "Yeşilova", "Ağlasun", "Altınyayla", "Çavdır", "Çeltikçi", "Karamanlı", "Kemer"],
  "Bursa": ["Osmangazi", "Yıldırım", "Nilüfer", "Gürsu", "Kestel", "İnegöl", "Gemlik", "Mudanya", "Mustafakemalpaşa", "Karacabey", "Orhangazi", "İznik", "Yenişehir", "Büyükorhan", "Harmancık", "Keles", "Orhaneli"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu", "Ezine", "Ayvacık", "Bayramiç", "Lapseki", "Gökçeada", "Bozcaada", "Eceabat", "Yenice"],
  "Çankırı": ["Merkez", "Çerkeş", "Ilgaz", "Şabanözü", "Kurşunlu", "Yapraklı", "Atkaracalar", "Bayramören", "Eldivan", "Kızılırmak", "Korgun", "Orta"],
  "Çorum": ["Merkez", "Sungurlu", "Alaca", "Osmancık", "İskilip", "Bayat", "Kargı", "Mecitözü", "Ortaköy", "Dodurga", "Laçin", "Oğuzlar", "Uğurludağ", "Boğazkale"],
  "Denizli": ["Merkezefendi", "Pamukkale", "Çivril", "Acıpayam", "Tavas", "Buldan", "Çal", "Çameli", "Güney", "Kale", "Sarayköy", "Honaz", "Serinhisar", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Babadağ"],
  "Diyarbakır": ["Bağlar", "Kayapınar", "Sur", "Yenişehir", "Bismil", "Ergani", "Silvan", "Çermik", "Dicle", "Çınar", "Çüngüş", "Eğil", "Hani", "Hazro", "Kocaköy", "Kulp", "Lice"],
  "Edirne": ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Enez", "Lalapaşa", "Meriç", "Süloğlu"],
  "Elazığ": ["Merkez", "Kovancılar", "Karakoçan", "Baskil", "Maden", "Palu", "Sivrice", "Ağın", "Alacakaya", "Arıcak", "Keban"],
  "Erzincan": ["Merkez", "Tercan", "Üzümlü", "Refahiye", "Çayırlı", "İliç", "Kemah", "Kemaliye", "Otlukbeli"],
  "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Oltu", "Horasan", "Pasinler", "Hınıs", "Karayazı", "Aşkale", "İspir", "Tekman", "Tortum", "Çat", "Karaçoban", "Köprüköy", "Narman", "Olur", "Pazaryolu", "Şenkaya", "Uzundere"],
  "Eskişehir": ["Odunpazarı", "Tepebaşı", "Çifteler", "Sivrihisar", "Alpu", "Beylikova", "Günyüzü", "Han", "İnönü", "Mahmudiye", "Mihalgazi", "Mihalıççık", "Sarıcakaya", "Seyitgazi"],
  "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Oğuzeli", "Araban", "Karkamış", "Yavuzeli"],
  "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Keşap", "Dereli", "Eynesil", "Piraziz", "Şebinkarahisar", "Alucra", "Çamoluk", "Çanakçı", "Doğankent", "Güce", "Yağlıdere"],
  "Gümüşhane": ["Merkez", "Kelkit", "Şiran", "Torul", "Köse", "Kürtün"],
  "Hakkari": ["Merkez", "Yüksekova", "Çukurca", "Şemdinli", "Derecik"],
  "Hatay": ["Antakya", "İskenderun", "Defne", "Arsuz", "Payas", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı", "Altınözü", "Belen", "Erzin", "Hassa", "Kumlu", "Yayladağı"],
  "Iğdır": ["Merkez", "Aralık", "Tuzluca", "Karakoyunlu"],
  "Isparta": ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Senirkent", "Keçiborlu", "Sütçüler", "Aksu", "Atabey", "Gönen", "Uluborlu", "Yenişarbademli"],
  "İstanbul": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"],
  "İzmir": ["Konak", "Bornova", "Buca", "Karşıyaka", "Bayraklı", "Çiğli", "Gaziemir", "Karabağlar", "Menemen", "Torbalı", "Kemalpaşa", "Ödemiş", "Bergama", "Tire", "Aliağa", "Foça", "Seferihisar", "Urla", "Çeşme", "Dikili", "Kiraz", "Menderes", "Selçuk", "Bayındır", "Beydağ", "Güzelbahçe", "Karaburun", "Kınık", "Narlıdere"],
  "Kahramanmaraş": ["Dulkadiroğlu", "Onikişubat", "Elbistan", "Afşin", "Göksun", "Türkoğlu", "Pazarcık", "Andırın", "Çağlayancerit", "Ekinözü", "Nurhak"],
  "Karabük": ["Merkez", "Safranbolu", "Eskipazar", "Ovacık", "Eflani", "Yenice"],
  "Karaman": ["Merkez", "Ermenek", "Ayrancı", "Başyayla", "Kazımkarabekir", "Sarıveliler"],
  "Kars": ["Merkez", "Sarıkamış", "Kağızman", "Selim", "Akyaka", "Arpaçay", "Digor", "Susuz"],
  "Kastamonu": ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Araç", "Çankırı", "Daday", "Devrekani", "Cide", "Küre", "Abana", "Ağlı", "Azdavay", "Bozkurt", "Doğanyurt", "Hanönü", "İhsangazi", "Pınarbaşı", "Seydiler", "Şenpazar"],
  "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Hacılar", "İncesu", "Develi", "Bünyan", "Yeşilhisar", "Tomarza", "Pınarbaşı", "Sarıoğlan", "Sarız", "Akkışla", "Felahiye", "Özvatan", "Yahyalı"],
  "Kırıkkale": ["Merkez", "Keskin", "Delice", "Sulakyurt", "Yahşihan", "Balışeyh", "Bahşılı", "Çelebi", "Karakeçili"],
  "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Kofçaz", "Pehlivanköy"],
  "Kırşehir": ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Akçakent", "Boztepe"],
  "Kilis": ["Merkez", "Elbeyli", "Musabeyli", "Polateli"],
  "Kocaeli": ["İzmit", "Gebze", "Darıca", "Çayırova", "Dilovası", "Gölcük", "Kandıra", "Karamürsel", "Kartepe", "Körfez", "Derince", "Başiskele"],
  "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Cihanbeyli", "Çumra", "Ilgın", "Kulu", "Seydişehir", "Karapınar", "Bozkır", "Doğanhisar", "Hadim", "Hüyük", "Kadınhanı", "Sarayönü", "Yunak", "Altınekin", "Ahırlı", "Çeltik", "Derbent", "Derebucak", "Emirgazi", "Güneysınır", "Halkapınar", "Taşkent", "Tuzlukçu", "Yalıhüyük"],
  "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Altıntaş", "Aslanapa", "Çavdarhisar", "Domaniç", "Dumlupınar", "Hisarcık", "Pazarlar", "Şaphane"],
  "Malatya": ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Arapgir", "Arguvan", "Doğanyol", "Kale", "Kuluncak", "Pütürge", "Yazıhan"],
  "Manisa": ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Saruhanlı", "Demirci", "Kırkağaç", "Gördes", "Sarıgöl", "Kula", "Ahmetli", "Gölmarmara", "Köprübaşı", "Selendi"],
  "Mardin": ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Ömerli", "Dargeçit", "Savur", "Yeşilli"],
  "Mersin": ["Akdeniz", "Mezitli", "Toroslar", "Yenişehir", "Tarsus", "Silifke", "Erdemli", "Anamur", "Mut", "Gülnar", "Aydıncık", "Bozyazı", "Çamlıyayla"],
  "Muğla": ["Menteşe", "Bodrum", "Fethiye", "Milas", "Marmaris", "Dalaman", "Ortaca", "Datça", "Köyceğiz", "Seydikemer", "Ula", "Kavaklidere", "Yatağan"],
  "Muş": ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"],
  "Nevşehir": ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Hacıbektaş", "Kozaklı", "Derinkuyu", "Acıgöl"],
  "Niğde": ["Merkez", "Bor", "Ulukışla", "Çamardı", "Altunhisar", "Çiftlik"],
  "Ordu": ["Altınordu", "Ünye", "Fatsa", "Perşembe", "Akkuş", "Aybastı", "Çamaş", "Çatalpınar", "Çaybaşı", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Ulubey"],
  "Osmaniye": ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Hasanbeyli", "Sumbas", "Toprakkale"],
  "Rize": ["Merkez", "Çayelçi", "Ardeşen", "Pazar", "Fındıklı", "İkizdere", "Çamlıhemşin", "Derepazarı", "Güneysu", "Hemşin", "İyidere", "Kalkandere"],
  "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Arifiye", "Hendek", "Akyazı", "Geyve", "Kaynarca", "Pamukova", "Sapanca", "Söğütlü", "Taraklı", "Ferizli", "Karapürçek", "Kocaali"],
  "Samsun": ["Atakum", "İlkadım", "Canik", "Tekkeköy", "Bafra", "Çarşamba", "Terme", "Vezirköprü", "Havza", "Alaçam", "Kavak", "Ladik", "Salıpazarı", "Ayvacık", "Asarcık", "Yakakent", "19 Mayıs"],
  "Siirt": ["Merkez", "Kurtalan", "Pervari", "Baykan", "Eruh", "Şirvan", "Tillo"],
  "Sinop": ["Merkez", "Boyabat", "Gerze", "Ayancık", "Türkeli", "Durağan", "Dikmen", "Erfelek", "Saraydüzü"],
  "Sivas": ["Merkez", "Şarkışla", "Suşehri", "Zara", "Gemerek", "Kangal", "Divriği", "Gürün", "Hafik", "İmranlı", "Koyulhisar", "Altınyayla", "Akıncılar", "Doğanşar", "Gölova", "Ulaş", "Yıldızeli"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç", "Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Halfeti", "Harran", "Hilvan"],
  "Şırnak": ["Merkez", "Cizre", "Silopi", "İdil", "Beytüşşebap", "Güçlükonak", "Uludere"],
  "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Ergene", "Kapaklı", "Hayrabolu", "Malkara", "Muratlı", "Saray", "Şarköy", "Marmaraereğlisi"],
  "Tokat": ["Merkez", "Turhal", "Erbaa", "Niksar", "Zile", "Reşadiye", "Almus", "Artova", "Başçiftlik", "Pazar", "Sulusaray", "Yeşilyurt"],
  "Trabzon": ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin", "Sürmene", "Çarşıbaşı", "Beşikdüzü", "Vakfıkebir", "Maçka", "Tonya", "Düzköy", "Çaykara", "Dernekpazarı", "Hayrat", "Köprübaşı", "Şalpazarı"],
  "Tunceli": ["Merkez", "Pertek", "Çemişgezek", "Hozat", "Mazgirt", "Nazımiye", "Ovacık", "Pülümür"],
  "Uşak": ["Merkez", "Eşme", "Banaz", "Sivaslı", "Ulubey", "Karahallı"],
  "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Başkale", "Çaldıran", "Gevaş", "Gürpınar", "Muradiye", "Özalp", "Saray", "Çatak", "Bahçesaray"],
  "Yalova": ["Merkez", "Çınarcık", "Çiftlikköy", "Altınova", "Armutlu", "Termal"],
  "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni", "Boğazlıyan", "Yerköy", "Sarıkaya", "Çekerek", "Şefaatli", "Aydıncık", "Çandır", "Çayıralan", "Kadışehri", "Saraykent", "Yenifakılı"],
  "Zonguldak": ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Alaplı", "Gökçebey", "Kilimli", "Kozlu"],
  "Düzce": ["Merkez", "Akçakoca", "Cumayeri", "Çilimli", "Gölyaka", "Gümüşova", "Kaynaşlı", "Yığılca"],
};

export const getIller = (): string[] => Object.keys(turkeyData).sort((a, b) => a.localeCompare(b, "tr"));

export const getIlceler = (il: string): string[] => turkeyData[il] || [];

export default turkeyData;
